spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphqls
    username: Gram
    password: Gram@2020
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9096
#graphql:
  #servlet.mapping: /odysseyauditservice