server:
  port: 9096
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphqls
    username: Gram
    password: Gram@2020
    initialization-mode: always
  jpa:
    dproperties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
graphql:
  spqr:
    http:
      endpoint: /sreesoft

